version: 0.2
env:
  variables:
    S3_BUCKET: "my-website-bucket"
    PROJECT: "DEV"
    COST_CENTER: "R423"
    parameter-store:
      OS_USER: "my_s3_bucket"
    secrets-manager:
      OS_PASSWORD: "dev/os_password:os_password"
phases: 
    install:
        runtime-versions:
            python: 3.9
        commands:
            - printenv
            - echo "installing something"
        finally:
            - echo "Install is completed"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - grep -Fq "Congratulations" index.html
        finally:
            - echo "Build is completed!!!"
    post_build:
        commands:
            - echo "we are in the post build phase"
